### ISSUE TITLE
MemoryError loading jumper.bmp

### ISSUE THREAD

**Issue by benallard** [python-ugame/jumper-wire#1]
```
main.py output:
Traceback (most recent call last):
  File "main.py", line 125, in <module>
  File "stage.py", line 212, in from_bmp16
  File "stage.py", line 180, in read_data
MemoryError: memory allocation failed, allocating 2048 bytes
```

**Comment by deshipu** [comment]
Are you running this at startup, or is there something else you loaded to memory before it? The game is a bit tight on memory, but it should run fine right after a reset.
